# Generated by Django 6.0.4 on 2026-04-29 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_topicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_sub_topicos', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sub_topicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista_tarefas.topicos')),
            ],
            options={
                'verbose_name_plural': 'sub_topicos_s',
            },
        ),
    ]
